version: "1.0"
services:
  postgresql:
    image: ${POSTGRES_IMAGE}
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${VOLUME_ROOT}/data:/bitnami/postgresql
      - ${VOLUME_ROOT}/init.sql:/docker-entrypoint-initdb.d/init.sql